# paper_figures/check_inputs.jl
#
# Verify that every input each figure needs is actually on disk BEFORE a reviewer
# spends hours discovering it is not.  Reports, per figure, which inputs are present
# and which are missing — and for each missing one, the script that produces it.
#
# Run from the repository root:
#   julia --project paper_figures/check_inputs.jl            # all figures
#   julia --project paper_figures/check_inputs.jl <id> ...   # selected figures
#
# Exit status is 0 if everything needed is present, 1 otherwise, so this is usable
# as a gate in a batch script.

include(joinpath(@__DIR__, "manifest.jl"))
using Printf

human(b) = b >= 1e9 ? @sprintf("%.1f GB", b/1e9) :
           b >= 1e6 ? @sprintf("%.1f MB", b/1e6) :
           b >= 1e3 ? @sprintf("%.1f KB", b/1e3) : @sprintf("%d B", b)

sel = isempty(ARGS) ? FIGURES : [figure_by_id(a) for a in ARGS]

# A function, not a top-level loop: at top level a `for` opens a soft scope, so
# `n_missing_total += 1` would create a fresh local and reading it afterwards throws.
function check_all(sel)
n_missing_total = 0
external_missing = String[]

for f in sel
    println("\n", "═"^78)
    println(f.id)
    println("  ", replace(f.title, r"\s+" => " "))
    println("═"^78)

    scr = joinpath(REPO, f.script)
    @printf("  %-8s %s%s\n", "script", f.script, isfile(scr) ? "" : "   ← MISSING")
    isfile(scr) || (n_missing_total += 1)

    present = 0
    for (path, producer, note) in f.inputs
        full = joinpath(REPO, path)
        if isfile(full)
            present += 1
            @printf("  [ok]   %-72s %10s\n", path, human(filesize(full)))
        else
            n_missing_total += 1
            @printf("  [MISS] %s\n", path)
            if producer === :external
                @printf("         └─ EXTERNAL data root — not reproducible from this repo%s\n",
                        isempty(note) ? "" : " ($note)")
                push!(external_missing, path)
            elseif producer === :repo
                println("         └─ should be in the repository; check your checkout")
            else
                println("         └─ produced by: $producer")
                isempty(note) || println("            ($note)")
                startswith(path, "models/") && occursin("build_model", producer) &&
                    println("            NB: a refit, not a byte-identical restore of ours")
            end
        end
    end
    @printf("  inputs: %d/%d present\n", present, length(f.inputs))

    done = count(o -> isfile(joinpath(REPO, o)), f.outputs)
    @printf("  outputs already on disk: %d/%d%s\n", done, length(f.outputs),
            done == length(f.outputs) ? "  (re-running will overwrite)" : "")
end
return n_missing_total, external_missing
end

n_missing_total, external_missing = check_all(sel)

println("\n", "─"^78)
if n_missing_total == 0
    println("All inputs present. Build with:  julia --project paper_figures/make_figures.jl")
else
    @printf("%d missing item(s).\n", n_missing_total)
    if !isempty(external_missing)
        println("\nThe external data roots below are NOT tracked by git (.gitignore excludes")
        println("models/, results/, *.csv, *.xyz, *.json), so they must come from the data")
        println("archive that accompanies the paper:")
        for p in unique(external_missing); println("  ", p); end
    end
    println("\nEverything else can be regenerated by running the listed producer scripts,")
    println("in dependency order, from the repository root.")
end
exit(n_missing_total == 0 ? 0 : 1)
