# standalone_repo/build_repo.jl
#
# Assemble the standalone reproduction repository from this working tree.
#
#   julia --project standalone_repo/build_repo.jl [target_dir]
#
# Copies the code and tier A, computes a SHA-256 for every declared file (both tiers),
# writes data/manifest.toml, and emits the repo's own README, .gitignore, run_all.sh and
# scripts/fetch_data.sh.  Tier B is NOT copied — it is listed for `make_tierB_archive.sh`
# to tar up separately, because 7.9 GB does not belong in git.
#
# Env:  TARGET  (default ../physics-informed-priors-repro)
#       TIERB_URL   base URL the fetch script will pull the archive from
#       SKIP_HASH=1 skip SHA-256 of tier B (it hashes 7.9 GB and takes minutes)

using SHA, Printf, Dates

ROOT   = normpath(joinpath(@__DIR__, ".."))
include(joinpath(@__DIR__, "manifest.jl"))

TARGET    = normpath(get(ENV, "TARGET", length(ARGS) >= 1 ? ARGS[1] :
                         joinpath(ROOT, "..", "physics-informed-priors-repro")))
TIERB_URL = get(ENV, "TIERB_URL", "https://zenodo.org/records/PLACEHOLDER/files")
SKIP_HASH = get(ENV, "SKIP_HASH", "0") != "0"

@printf("source : %s\ntarget : %s\n\n", ROOT, TARGET)

sha256_file(p) = open(p) do io; bytes2hex(SHA.sha256(io)); end

function copy_entry(src, dst)
    mkpath(dirname(dst))
    isdir(src) ? cp(src, dst; force=true, follow_symlinks=true) : cp(src, dst; force=true)
end

# ── code + tier A ────────────────────────────────────────────────────────────
n_code = n_A = 0; bytes_A = 0
for f in FILES
    global n_code, n_A, bytes_A
    f.tier === :B && continue
    src = joinpath(ROOT, f.path)
    ispath(src) || (@warn "missing, skipped" path=f.path; continue)
    copy_entry(src, joinpath(TARGET, f.path))
    if f.tier === :code
        n_code += 1
    else
        n_A += 1; bytes_A += isfile(src) ? filesize(src) : 0
    end
end
@printf("copied %d code entries and %d tier-A files (%.1f MB)\n", n_code, n_A, bytes_A/1e6)

# Prune anything that rode in on a recursive directory copy without belonging here.
for x in EXCLUDE
    p = joinpath(TARGET, x)
    ispath(p) && (rm(p; recursive=true, force=true); println("pruned (EXCLUDE): ", x))
end

# ── data/manifest.toml ───────────────────────────────────────────────────────
mkpath(joinpath(TARGET, "data"))
open(joinpath(TARGET, "data", "manifest.toml"), "w") do io
    println(io, "# Generated by standalone_repo/build_repo.jl on ",
                Dates.format(now(), "yyyy-mm-dd HH:MM"), ".  Do not edit by hand.")
    println(io, "#")
    println(io, "# tier = \"A\"  committed to this repository")
    println(io, "# tier = \"B\"  fetched separately — see scripts/fetch_data.sh")
    println(io, "# rebuildable  a cache, regenerable from the rest; a fetch may skip it")
    println(io, "# producer     the script that makes it, or \"external\" for a DFT root")
    println(io)
    for f in FILES
        f.tier === :code && continue
        src = joinpath(ROOT, f.path)
        isfile(src) || continue
        h = (f.tier === :B && SKIP_HASH) ? "" : sha256_file(src)
        println(io, "[[file]]")
        println(io, "path        = \"", f.path, "\"")
        println(io, "tier        = \"", f.tier === :A ? "A" : "B", "\"")
        println(io, "bytes       = ", filesize(src))
        isempty(h) || println(io, "sha256      = \"", h, "\"")
        println(io, "producer    = \"", f.producer === :external ? "external" : String(f.producer), "\"")
        f.rebuildable && println(io, "rebuildable = true")
        println(io, "note        = \"", replace(f.note, "\"" => "'"), "\"")
        println(io)
        print(stderr, ".")
    end
end
println("\nwrote data/manifest.toml")

# ── the repo's own .gitignore ────────────────────────────────────────────────
# THIS IS THE ONE THAT BITES.  The source repo's .gitignore excludes *.csv, *.json,
# *.xyz and models/ — which is the whole of tier A.  Copied across, the repository would
# look complete and contain nothing.
write(joinpath(TARGET, ".gitignore"), """
# Tier B: fetched, never committed.  See scripts/fetch_data.sh and data/manifest.toml.
models/*/A.csv
models/*/results/cutting_plane_full_cloud/committee_stable.jls
models/*/results/cutting_plane_full_cloud/committee_full_cloud*.jls
models/*/results/cutting_plane_full_cloud/member_diagnostics.csv
models/*/results/undotted_Hbasis_*.jls
models/*/results/*/bandpath_*_aref.jls
data/Al/
data/W/

# Reproduction output.  Every pipeline stage writes here; none of it is the paper's.
models/*/results/repro_*/
models/*/repro_*.csv
scripts/uq/rls_constrained_pops_Al_12/repro_*/
scripts/uq/rls_constrained_pops_Al_12/logs/
scripts/uq/rls_constrained_pops_Al_12/npt/*/T200K/md_trajectory.extxyz
**/repro_*.pdf
**/repro_*.png

# Julia, LaTeX, editors
*.jl.cov
*.jl.mem
/docs/build/
*.aux
*.log
*.out
*.synctex.gz
.vscode/
.CondaPkg/

# NOTE: tier A is *.csv, *.json and *.jls under models/ and it IS tracked.
# Do not add a blanket *.csv rule here — the source repository has one, and copying it
# across is how you get a repository that looks complete and contains no data.
""")
println("wrote .gitignore")

# ── fetch_data.sh ────────────────────────────────────────────────────────────
mkpath(joinpath(TARGET, "scripts"))
fetch = joinpath(TARGET, "scripts", "fetch_data.sh")
write(fetch, """
#!/bin/bash
# fetch_data.sh — pull the tier-B archive and verify it against data/manifest.toml.
#
#   bash scripts/fetch_data.sh            # fetch, extract, verify
#   bash scripts/fetch_data.sh verify     # verify what is already on disk
#   bash scripts/fetch_data.sh --no-cache # skip the rebuildable caches (saves 443 MB)
#
# Tier B is $(Int(round(sum(filesize(joinpath(ROOT,f.path)) for f in tier(:B) if isfile(joinpath(ROOT,f.path)))/1e9*100))/100) GB, dominated by the three design matrices.
# Tier A is already in the repository; you do not need this to run `run_all.sh replot`.
set -euo pipefail
ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
URL=\${TIERB_URL:-$TIERB_URL}
ARCHIVE=\${ARCHIVE:-"\$ROOT/tierB.tar"}
MODE=\${1:-fetch}

verify() {
  python3 - "\$ROOT" <<'PY'
import hashlib, sys, os, re
root = sys.argv[1]
txt = open(os.path.join(root, "data", "manifest.toml")).read()
ok = missing = bad = 0
for block in txt.split("[[file]]")[1:]:
    g = lambda k: (re.search(rf'^{k}\\s*=\\s*"?([^"\\n]+)"?', block, re.M) or [None,None])[1]
    path, tier, want = g("path"), g("tier"), g("sha256")
    if tier != "B" or not want: continue
    full = os.path.join(root, path)
    if not os.path.exists(full):
        print(f"  MISSING  {path}"); missing += 1; continue
    h = hashlib.sha256()
    with open(full, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 22), b""): h.update(chunk)
    if h.hexdigest() == want: ok += 1
    else: print(f"  CORRUPT  {path}"); bad += 1
print(f"\\n{ok} verified, {missing} missing, {bad} corrupt")
sys.exit(1 if bad else 0)
PY
}

case "\$MODE" in
  verify) verify ;;
  *)
    echo "fetching tier B from \$URL"
    echo "NOTE: the URL above is a placeholder until the archive is deposited."
    [ -f "\$ARCHIVE" ] || curl -fL --progress-bar -o "\$ARCHIVE" "\$URL/tierB.tar"
    tar -xf "\$ARCHIVE" -C "\$ROOT"
    verify
    ;;
esac
""")
chmod(fetch, 0o755)
println("wrote scripts/fetch_data.sh")

# ── README and run_all.sh, from templates/ ───────────────────────────────────
for t in ("README.md", "run_all.sh")
    src = joinpath(@__DIR__, "templates", t)
    cp(src, joinpath(TARGET, t); force=true)
    t == "run_all.sh" && chmod(joinpath(TARGET, t), 0o755)
    println("wrote ", t)
end

# ── the tier-B archive builder, run on the SOURCE side ───────────────────────
tarsh = joinpath(@__DIR__, "make_tierB_archive.sh")
open(tarsh, "w") do io
    println(io, "#!/bin/bash")
    println(io, "# Generated by build_repo.jl.  Tars tier B for deposit, from the SOURCE tree.")
    println(io, "set -euo pipefail")
    println(io, "cd \"", ROOT, "\"")
    println(io, "tar -cvf \"\${OUT:-", TARGET, "/tierB.tar}\" \\")
    paths = [f.path for f in tier(:B) if isfile(joinpath(ROOT, f.path))]
    for (i, p) in enumerate(paths)
        println(io, "  ", "\"", p, "\"", i == length(paths) ? "" : " \\")
    end
    println(io, "echo \"tier B archive → \${OUT:-", TARGET, "/tierB.tar}\"")
end
chmod(tarsh, 0o755)
println("wrote standalone_repo/make_tierB_archive.sh")

@printf("\n══ done.  %s\n", TARGET)
println("next:  bash standalone_repo/make_tierB_archive.sh    # 7.9 GB, minutes")
println("       cd $TARGET && git init && git add -A && git commit")
