#!/bin/bash
# Generated by build_repo.jl.  Tars tier B for deposit, from the SOURCE tree.
set -euo pipefail
cd "/storage/astro2/phupfb/PhD/acestuff/ACEWorkflow/"
tar -cvf "${OUT:-/storage/astro2/phupfb/PhD/acestuff/physics-informed-priors-repro/tierB.tar}" \
  "scripts/uq/rls_constrained_pops_Al_12/npt/rls/T200K/md_trajectory.extxyz" \
  "scripts/uq/rls_constrained_pops_Al_12/npt/constrained/T200K/md_trajectory.extxyz" \
  "models/Al_12_4_6A_2_/A.csv" \
  "models/Al_16_4_6A_3_/A.csv" \
  "models/W_20_4_5A_3/A.csv" \
  "models/Al_12_4_6A_2_/results/cutting_plane_full_cloud/committee_stable.jls" \
  "models/Al_12_4_6A_2_/results/cutting_plane_full_cloud/member_diagnostics.csv" \
  "models/Al_12_4_6A_2_/results/undotted_Hbasis_4x4x4_a4.04494.jls" \
  "models/Al_16_4_6A_3_/results/pinned_ensembles/bandpath_4x4x4_aref.jls" \
  "data/Al/manual_df_train_Al.extxyz" \
  "data/Al/manual_df_test_Al.xyz" \
  "data/W/df_W_train.extxyz"
echo "tier B archive → ${OUT:-/storage/astro2/phupfb/PhD/acestuff/physics-informed-priors-repro/tierB.tar}"
