# elastic_constraints_rejection.jl
#
# Same constrained-QP workflow as elastic_constraints.jl (kept as the legacy
# reference), but the committee is generated by REJECTION SAMPLING instead of
# percentile clipping:
#   - the hypercube proposal over the constrained-POPS solutions is UNCLIPPED
#     (percentile_clipping = 0), and
#   - each draw c is accepted only if it satisfies the physical inequality
#     constraints l ≤ A c ≤ u (C44, C11−C12, C11+2C12, lattice curvature),
# so the accepted ensemble is honestly distributed over
# (hypercube ∩ feasible set) rather than over a percentile-shrunk box.
#
# Model: Al_14_4_6A_2, subset_20_percent.

using LinearAlgebra, Statistics, DelimitedFiles, Printf
using SparseArrays, StaticArrays
using Test
using ACEpotentials, ForwardDiff, Unitful, ACEWorkflow
using OSQP

element    = :Al

# ── Load model ────────────────────────────────────────────────────────────────
result     = load_model(element, 14, 4, 6, 2; dataset_name="subset_20_percent")
model      = result.model
A          = result.A
Y          = result.Y
P          = result.P
W          = result.W
lin_params = result.lin_params

Ap = Diagonal(W) * A / P
Yw = W .* Y

# ── Equilibrium lattice constant and Hessian basis ────────────────────────────
println("Relaxing equilibrium lattice constant ...")
a_eq = ACEWorkflow.relax_lattice_constant(model, element)
@printf("a_eq = %.6f Å\n", a_eq)

println("Computing strain Hessian basis at a_eq ...")
C, H_eq, _ = ACEWorkflow.Elasticity.strain_hessian_GPa(model, element; a=a_eq)

# ── Lattice basis derivative for equilibrium constraint ───────────────────────
function lattice_basis(a_val)
    sys = ACEWorkflow.Elasticity.reference_system(element; a=a_val)
    ustrip.(u"eV", ACEpotentials.Models.potential_energy_basis(sys, model))
end

println("Computing b′ ...")
b_prime = ForwardDiff.derivative(lattice_basis, a_eq)

println("Computing b″ ...")
b_double_prime = ForwardDiff.derivative(a -> ForwardDiff.derivative(lattice_basis, a), a_eq)

# ── Constrained ridge regression ──────────────────────────────────────────────
function constrained_ridge_regression(X_train, Y_train, Gamma, constraint_matrix, constraint_bounds; lambda = 1.0 / size(X_train, 1))
    H = (X_train' * X_train .+ (lambda .* Gamma' * Gamma))
    b = - X_train' * Y_train
    osqp_model = OSQP.Model()
    OSQP.setup!(osqp_model; P=sparse(H), q=b, A=sparse(constraint_matrix / Gamma), l=constraint_bounds[1], u=constraint_bounds[2],
                max_iter=5_000_000_000, check_termination=1_000, verbose=true, eps_abs=1e-4, eps_rel=1e-4)
    results = OSQP.solve!(osqp_model)
    return Gamma \ results.x
end

# ── Constraint vectors ────────────────────────────────────────────────────────
constraint_1 = H_eq[1,1,:]
C11_lower    = dot(constraint_1, lin_params)
C11_upper    = dot(constraint_1, lin_params)

constraint_2 = H_eq[1,2,:]
C12_lower    = dot(constraint_2, lin_params)
C12_upper    = dot(constraint_2, lin_params)

constraint_4 = H_eq[4,4,:]
C44_lower    = 0.1
C44_upper    = Inf

# Born stability: C11 + 2*C12 > 0
C11_plus_2C12_constraint = constraint_1 .+ 2 .* constraint_2
C11_plus_2C12_lower      = 0.1
C11_plus_2C12_upper      = Inf

C12_less_than_C11_constraint = constraint_1 .- constraint_2
C12_less_than_C11_lower      = 1.0
C12_less_than_C11_upper      = Inf

# Lattice constant constraint: b′(a_eq) · θ = 0
# Ensures the correction δθ does not shift the equilibrium lattice constant.
lattice_eq_constraint = b_prime                          # n_params-vector
lattice_eq_lower      = 0.0
lattice_eq_upper      = 0.0

# Lattice curvature constraint: b″(a_eq) · θ > 0
# a_eq must remain a minimum (not a maximum/saddle) of E(a).
lattice_curvature_constraint = b_double_prime            # n_params-vector
lattice_curvature_lower      = 1e-9
lattice_curvature_upper      = Inf

all_constraints = vcat(constraint_1',
                       constraint_4',
                       C12_less_than_C11_constraint',
                       C11_plus_2C12_constraint',
                       lattice_eq_constraint',
                       lattice_curvature_constraint')
lower_bounds    = [C11_lower, C44_lower,
                   C12_less_than_C11_lower, C11_plus_2C12_lower,
                   lattice_eq_lower, lattice_curvature_lower]
upper_bounds    = [C11_upper, C44_upper,
                   C12_less_than_C11_upper, C11_plus_2C12_upper,
                   lattice_eq_upper, lattice_curvature_upper]

constraints = (lower_bounds, upper_bounds)

constrained_ridge_teta = constrained_ridge_regression(Ap, Yw, P, all_constraints, constraints)

function constrained_pops(X_train, Y_train, Gamma, constraint_matrix, constraint_bounds; members_to_constrain=1:length(Y_train))
    constrained_pops_parameters = zeros(length(members_to_constrain), size(X_train, 2))
    H = (X_train' * X_train .+ (1.0 / (size(X_train, 1)) .* Gamma' * Gamma))
    b = - X_train' * Y_train

    model = OSQP.Model()

    # QP variable is θ̃ = Γc: physical constraint rows (defined on c) map via
    # /Γ, but the data row X_train[i,:] is a row of Ap acting on θ̃ directly —
    # it must not be divided by Γ.  (The legacy constrained_pops divides both,
    # pinning Ap[i,:]·c instead of the prediction Ap[i,:]·θ̃.)
    constraint_tilde = constraint_matrix / Gamma

    for idx in 1:length(members_to_constrain)
        i = members_to_constrain[idx]
        l_full = vcat([Y_train[i]], constraint_bounds[1])
        u_full = vcat([Y_train[i]], constraint_bounds[2])
        A_sparse = sparse(vcat(X_train[i,:]', constraint_tilde))

        OSQP.setup!(model; P=sparse(H), q=b, A=A_sparse, l=l_full, u=u_full,
                    max_iter=500_000, check_termination=10, verbose=false, eps_abs=5e-4, eps_rel=5e-4)

        if (mod(idx, 100) == 0)
            println(idx)
        end
        results = OSQP.solve!(model)
        constrained_pops_parameters[idx,:] = Gamma \ results.x
    end
    return constrained_pops_parameters
end

constrained_pops_delta = constrained_pops(Ap, Yw, P, all_constraints, constraints)

# ── Committee via rejection sampling ─────────────────────────────────────────
# Unclipped hypercube proposal over the constrained-POPS solutions; a draw is
# kept only if the full coefficient vector satisfies the physical inequality
# constraints l ≤ A c ≤ u.  The equality rows (C11/C12 pins, lattice b′·c = 0)
# have zero acceptance probability under a continuous proposal and are NOT
# enforced here; every constrained-POPS solution the proposal is built from
# already satisfies them to solver tolerance.
ineq_constraint_matrix = vcat(constraint_4',
                              C12_less_than_C11_constraint',
                              C11_plus_2C12_constraint',
                              lattice_curvature_constraint')
ineq_bounds = ([C44_lower, C12_less_than_C11_lower, C11_plus_2C12_lower, lattice_curvature_lower],
               [C44_upper, C12_less_than_C11_upper, C11_plus_2C12_upper, lattice_curvature_upper])

pops_eig, pops_bound = hypercube(constrained_pops_delta)   # percentile_clipping = 0 → unclipped
pops_samples, _ = rejection_sample_hypercube(pops_eig, pops_bound,
                                             zeros(length(constrained_ridge_teta)),
                                             ineq_constraint_matrix, ineq_bounds)
pops_samples = [pops_samples[:,i] for i=1:size(pops_samples,2)]
writedlm("$(result.dir)/rejection_sampled_constrained_pops_samples.csv", pops_samples, ',')

ACEpotentials.Models.set_linear_parameters!(model, constrained_ridge_teta)
a_eq = ACEWorkflow.relax_lattice_constant(model, element)

# ── eV → GPa conversion ───────────────────────────────────────────────────────
sys0      = ACEWorkflow.Elasticity.reference_system(element; a=a_eq)
L0        = SMatrix{3,3,Float64}(ustrip.(ACEWorkflow.Elasticity.lattice_matrix(sys0.cell.cell_vectors)))
V         = abs(det(L0))
eV_to_GPa = 160.2176621 / V

# ── Elastic constants from constrained solution ───────────────────────────────
C11_c = dot(H_eq[1,1,:], constrained_ridge_teta) * eV_to_GPa
C12_c = dot(H_eq[1,2,:], constrained_ridge_teta) * eV_to_GPa
C44_c = dot(H_eq[4,4,:], constrained_ridge_teta) * eV_to_GPa

C11_nom = C11_lower * eV_to_GPa   # nominal (from lin_params)
C12_nom = C12_lower * eV_to_GPa
C44_nom = dot(constraint_4, lin_params) * eV_to_GPa

println()
println("── Elastic constants ───────────────────────────────────────")
@printf("           %10s  %10s\n", "nominal", "constrained")
@printf("  C11  =   %8.3f    %8.3f  GPa\n", C11_nom, C11_c)
@printf("  C12  =   %8.3f    %8.3f  GPa\n", C12_nom, C12_c)
@printf("  C44  =   %8.3f    %8.3f  GPa\n", C44_nom, C44_c)
@printf("  C11-C12  = %8.3f  GPa  (Born: must be > 0)\n", C11_c - C12_c)
@printf("  C11+2C12 = %8.3f  GPa  (Born: must be > 0)\n", C11_c + 2*C12_c)

println()
println("── Constraint checks ───────────────────────────────────────")

# 1. C11 equality
@printf("  C11 equality:          |Δ| = %.3e GPa", abs(C11_c - C11_nom))
@test abs(C11_c - C11_nom) < 0.1
println(abs(C11_c - C11_nom) < 0.1 ? "  ✓" : "  ✗")

# 2. Born: C11 > C12
@printf("  Born C11 - C12:        %.3f GPa", C11_c - C12_c)
@test C11_c - C12_c > 0
println(C11_c - C12_c > 0 ? "  ✓" : "  ✗")

# 3. Born: C11 + 2*C12 > 0
@printf("  Born C11 + 2*C12:      %.3f GPa", C11_c + 2*C12_c)
@test C11_c + 2*C12_c > 0
println(C11_c + 2*C12_c > 0 ? "  ✓" : "  ✗")

# 4. Lattice constant: b′·c = 0
lattice_residual = dot(b_prime, constrained_ridge_teta)
@printf("  Lattice b′·c:          %.3e eV/Å", lattice_residual)
@test abs(lattice_residual) < 1e-4
println(abs(lattice_residual) < 1e-4 ? "  ✓" : "  ✗")

# 5. Lattice curvature: b″·c > 0
lattice_curvature = dot(b_double_prime, constrained_ridge_teta)
@printf("  Lattice b″·c (curvature): %.3e eV/Å²", lattice_curvature)
@test lattice_curvature > 0
println(lattice_curvature > 0 ? "  ✓" : "  ✗")

# ── Committee-wide constraint verification ────────────────────────────────────
# Every accepted member must satisfy the inequality set by construction.
println()
println("── Committee (rejection-sampled) constraint checks ─────────")
n_ok = count(c -> all(ineq_bounds[1] .<= ineq_constraint_matrix * c .<= ineq_bounds[2]),
             pops_samples)
@printf("  %d / %d accepted members satisfy l ≤ Ac ≤ u\n", n_ok, length(pops_samples))
@test n_ok == length(pops_samples)
